# fstring

In [1]:
name = 'World'
program = 'Python'

print(f"hello {name}..! this is {program}")

hello World..! this is Python


In [2]:
a=12
b=23

print(f"{a*b}")

276


In [69]:
for i in range(11):
    print(f"adasdasd{i*34}asdasdsad")

    

adasdasd0asdasdsad
adasdasd34asdasdsad
adasdasd68asdasdsad
adasdasd102asdasdsad
adasdasd136asdasdsad
adasdasd170asdasdsad
adasdasd204asdasdsad
adasdasd238asdasdsad
adasdasd272asdasdsad
adasdasd306asdasdsad
adasdasd340asdasdsad


In [53]:
class Employee:

    increment = 1.5
    no_of_employee = 0

    def __init__(self, fname, lname, salary):
        self.fname = fname
        self.lname = lname
        self.salary = salary
        #self.email = fname +lname+"@gmail.com"
        Employee.no_of_employee += 1

    def increase(self):
        self.salary = self.salary * Employee.increment

    @property
    def email(self):
        if self.fname == None:
            return "email not set"

        else:
            return self.fname + "." + self.lname + "@gmail.com"

    @email.setter
    def email(self, given_email):
        name_list = given_email.split("@")[0].split('.')
        self.fname = name_list[0]
        self.lname = name_list[1]

    @email.deleter
    def email(self):
        self.fname = None
        self.lname = None

    @classmethod
    def change_increment(cls, ammount):
        cls.increment = ammount

    @classmethod
    def from_string(cls, emp_string):
        fname, lname, salary = emp_string.split("-")
        return cls(fname, lname, salary)

    @classmethod
    def from_string1(cls, emp_string):
        fname, lname, salary = emp_string.split("--")
        return cls(fname, lname, salary)

    @staticmethod
    def is_open(day):
        if day == "sunday":
            return False
        else:
            return True

    def __add__(self, other):
        return self.salary - other.salary

    def __repr__(self):
        return "vijay profile"

    def __str__(self):
        return "sting profile"


class Programmer(Employee):
    def __init__(self, fname, lname, salary, prolang, exp):
        super().__init__(fname, lname, salary)
        self.prolang = prolang
        self.exp = exp


def increase(self):
    self.salary = self.salary * (self.increment + 0.2)




In [54]:
harry=Employee("hary","sharma",15000)

In [55]:
harry.email ="sddsf.sds@sdsd.com"

In [56]:
del harry.email

In [57]:
harry.email

'email not set'

In [58]:
Employee.is_open("sas")

True

In [59]:
add=(lambda x:x+x)

In [60]:
l=[1,2,3]


In [61]:
pp=map(add,l)

In [62]:
list(pp)

[2, 4, 6]

In [63]:
ff =(lambda x:x%2!=0)

In [64]:
list(map(ff,l))

[True, False, True]

In [16]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self,

In [17]:
keys = ['a', 'e', 'i', 'o', 'u']
value =[1,2,3,4,5]
vowels = dict.fromkeys(keys,value)

vowels

{'a': [1, 2, 3, 4, 5],
 'e': [1, 2, 3, 4, 5],
 'i': [1, 2, 3, 4, 5],
 'o': [1, 2, 3, 4, 5],
 'u': [1, 2, 3, 4, 5]}

In [18]:
person = {'name': 'Phill'}

In [19]:
person.setdefault('salary')

In [20]:
person

{'name': 'Phill', 'salary': None}

In [21]:
person.setdefault('age',232)

232

In [22]:
person

{'name': 'Phill', 'salary': None, 'age': 232}

In [23]:
d = {1: "one", 2: "three"}
d1 = {2: "two"}

d.update(d1)

In [24]:
d

{1: 'one', 2: 'two'}

In [25]:
d = {'x': 2}

d.update(y = 3, z = 0,a=12)

In [26]:
d

{'x': 2, 'y': 3, 'z': 0, 'a': 12}

In [27]:
p=[7,8,9]
v=[4]
d.fromkeys(p,v)

{7: [4], 8: [4], 9: [4]}

In [28]:
d

{'x': 2, 'y': 3, 'z': 0, 'a': 12}

In [29]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

element = sales.pop("sads",223423)

In [30]:
element

223423

In [31]:
def a():
    print('Hello World')
    return 42

def f():
    return a()

def g():
    a()



In [32]:
frv=f()
print(frv)

Hello World
42


In [33]:
grv=g()
print(grv)

Hello World
None


In [34]:
arv=a()
print(arv)

Hello World
42


In [35]:
def decorated_func(original_func):
    def wrapper_func(*args,**kwargs):
        print(f"wrapper executed this before  {original_func.__name__}")
        return original_func(*args,*kwargs)
    return wrapper_func

In [36]:

def of():
    print("main fuction ran")

In [37]:
of()

main fuction ran


In [38]:
pp=decorated_func(of)

In [39]:
pp()

wrapper executed this before  of
main fuction ran


In [40]:
@decorated_func
def off():
    return 7

In [41]:
off()

wrapper executed this before  off


7

In [42]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])


In [43]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [44]:
import re

text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
coreyms.com
321-555-4321
123.555.1234
123*555*1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
'''

sentence = 'Start a sentence and then bring it to an end'

pattern = re.compile(r'start', re.I)

matches = pattern.search(sentence)

print(matches)

<re.Match object; span=(0, 5), match='Start'>


In [45]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4]])

In [46]:
C = np.dot(A, B)

In [47]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
B

array([[2],
       [4]])

In [49]:
C

array([[10],
       [22],
       [34]])

In [50]:
t = A.dot(B)

In [51]:
t

array([[10],
       [22],
       [34]])

In [52]:
help(A.dot)

Help on built-in function dot:

dot(...) method of numpy.ndarray instance
    a.dot(b, out=None)
    
    Dot product of two arrays.
    
    Refer to `numpy.dot` for full documentation.
    
    See Also
    --------
    numpy.dot : equivalent function
    
    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[2.,  2.],
           [2.,  2.]])
    
    This array method can be conveniently chained:
    
    >>> a.dot(b).dot(b)
    array([[8.,  8.],
           [8.,  8.]])

